theme: jekyll-theme-cayman

title: Homero Roman Roman
description_a: Microsoft Software Engineer
description_b: Masters in Computer Science

collections:
    experience:
    projects:
    publications: